-d C:\Users\haogang\Desktop\usb30_uvc\prj\impl\gwsynthesis\prj.vg
-p GW5AST-138B-FCPBGA676A-1
-pn GW5AST-LV138FPG676AES
-cst C:\Users\haogang\Desktop\usb30_uvc\prj\src\top.cst
-cfg C:\Users\haogang\Desktop\usb30_uvc\prj\impl\pnr\device.cfg
-sdc C:\Users\haogang\Desktop\usb30_uvc\prj\src\top.sdc
-bit
-tr
-ph
-timing
-ireg_not_in_iob
-oreg_not_in_iob
-ioreg_not_in_iob
-cst_error
-convert_sdp32_36_to_sdp16_18
-correct_hold 1
-route_maxfan 23
-global_freq 100.000
-enable_dsrm 0
-csr C:/Users/haogang/Desktop/usb30_uvc/prj/src/serdes/serdes.csr
