`define USER_ENDPT1_IN
`define USER_ENDPT2_IN
//`define USER_ENDPT3_IN
//`define USER_ENDPT4_IN
//`define USER_ENDPT5_IN
//`define USER_ENDPT6_IN
//`define USER_ENDPT7_IN
//`define USER_ENDPT8_IN
//`define USER_ENDPT9_IN
//`define USER_ENDPT10_IN
//`define USER_ENDPT11_IN
//`define USER_ENDPT12_IN
//`define USER_ENDPT13_IN
//`define USER_ENDPT14_IN
//`define USER_ENDPT15_IN
//`define USER_ENDPT16_IN

//`define USER_ENDPT1_OUT
//`define USER_ENDPT2_OUT
//`define USER_ENDPT3_OUT
//`define USER_ENDPT4_OUT
//`define USER_ENDPT5_OUT
//`define USER_ENDPT6_OUT
//`define USER_ENDPT7_OUT
//`define USER_ENDPT8_OUT
//`define USER_ENDPT9_OUT
//`define USER_ENDPT10_OUT
//`define USER_ENDPT11_OUT
//`define USER_ENDPT12_OUT
//`define USER_ENDPT13_OUT
//`define USER_ENDPT14_OUT
//`define USER_ENDPT15_OUT
//`define USER_ENDPT16_OUT